//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SON.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseMVCshoppingEntities : DbContext
    {
        public DatabaseMVCshoppingEntities()
            : base("name=DatabaseMVCshoppingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<categories> categories { get; set; }
        public DbSet<customers> customers { get; set; }
        public DbSet<orderdetails> orderdetails { get; set; }
        public DbSet<orders> orders { get; set; }
        public DbSet<products> products { get; set; }
    }
}
