//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SON.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetails
    {
        public int OrderID { get; set; }
        public Nullable<int> ProuctID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<short> Quantity { get; set; }
        public string Discount { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual products products { get; set; }
    }
}
