//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SON.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public products()
        {
            this.orderdetails = new HashSet<orderdetails>();
            this.orders = new HashSet<orders>();
        }
    
        public int ProuctID { get; set; }
        public string ProductName { get; set; }
        public string Price { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string QuantityPerUnit { get; set; }
        public string UnitsInStock { get; set; }
    
        public virtual categories categories { get; set; }
        public virtual ICollection<orderdetails> orderdetails { get; set; }
        public virtual ICollection<orders> orders { get; set; }
    }
}
